import { TestProjectBuilder } from "../TestProjectBuilder.js";

export async function createCraStorefrontProject() {
  return new TestProjectBuilder()
    .withTemplate("empty")
    .withFile(
      "package.json",
      JSON.stringify(
        {
          name: "realistic-cra-storefront",
          private: true,
          dependencies: {
            bootstrap: "^4.3.1",
            react: "^18.0.0",
            "react-dom": "^18.0.0",
            "react-router-dom": "^5.0.0",
          },
          scripts: {
            start: "react-scripts start",
            build: "react-scripts build",
          },
        },
        null,
        2,
      ) + "\n",
    )
    .withFile(
      "public/index.html",
      [
        "<!doctype html>",
        '<html lang="en">',
        "  <head>",
        '    <meta charset="utf-8" />',
        '    <meta name="viewport" content="width=device-width, initial-scale=1" />',
        "    <title>Storefront</title>",
        "  </head>",
        "  <body>",
        '    <div id="root"></div>',
        "  </body>",
        "</html>",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/index.js",
      [
        "import React from 'react';",
        "import ReactDOM from 'react-dom';",
        "import { BrowserRouter as Router } from 'react-router-dom';",
        "import './index.css';",
        "import App from './App';",
        "import { ProductProvider } from './state/ProductContext';",
        "import { ThemeProvider } from './theme/ThemeContext';",
        "import * as serviceWorker from './serviceWorker';",
        "",
        "ReactDOM.render(",
        "  <ProductProvider>",
        "    <ThemeProvider>",
        "      <Router>",
        "        <App />",
        "      </Router>",
        "    </ThemeProvider>",
        "  </ProductProvider>,",
        "  document.getElementById('root')",
        ");",
        "",
        "serviceWorker.unregister();",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/App.js",
      [
        "import React from 'react';",
        "import { Switch, Route } from 'react-router-dom';",
        "import './App.css';",
        "import 'bootstrap/dist/css/bootstrap.min.css';",
        "import Shell from './layout/Shell';",
        "import Navbar from './components/Navbar';",
        "import Modal from './components/Modal';",
        "import ProductList from './features/catalog/ProductList';",
        "import ProductDetails from './features/catalog/ProductDetails';",
        "import Cart from './features/cart';",
        "import NotFound from './routes/NotFound';",
        "",
        "export default function App() {",
        "  return (",
        '    <Shell className="app-root app-shell h-full">',
        "      <Navbar />",
        "      <Switch>",
        '        <Route exact path="/" component={ProductList} />',
        '        <Route path="/details" component={ProductDetails} />',
        '        <Route path="/cart" component={Cart} />',
        "        <Route component={NotFound} />",
        "      </Switch>",
        "      <Modal />",
        "    </Shell>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile("src/serviceWorker.js", "export function unregister() {}\n")
    .withSourceFile(
      "src/data/products.js",
      [
        "export const products = [",
        "  { id: 1, title: 'Camera', category: 'photo', featured: true, inStock: true },",
        "  { id: 2, title: 'Console', category: 'games', featured: false, inStock: true },",
        "  { id: 3, title: 'Tripod', category: 'photo', featured: false, inStock: false },",
        "];",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/state/ProductContext.js",
      [
        "import { products } from '../data/products';",
        "",
        "export function ProductProvider({ children }) {",
        "  return children;",
        "}",
        "",
        "export function ProductConsumer({ children }) {",
        "  return children({",
        "    products,",
        "    featured: products[0],",
        "    cart: products.slice(0, 2),",
        "    totals: { subtotal: 120, shipping: 8 },",
        "  });",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/theme/ThemeContext.js",
      [
        "export function ThemeProvider({ children }) {",
        "  return children;",
        "}",
        "",
        "export function ThemeConsumer({ children }) {",
        "  return children({ theme: 'dark', compact: false });",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/utils/classNames.js",
      [
        "export function joinClasses(...values) {",
        "  return values.filter(Boolean).join(' ');",
        "}",
        "",
        "export function statusClass(prefix, value) {",
        "  return value ? `${prefix}--active` : `${prefix}--idle`;",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/layout/index.js",
      [
        "export { default as Shell } from './Shell';",
        "export { default as Footer } from './Footer';",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/layout/Shell.js",
      [
        "import { joinClasses } from '../utils/classNames';",
        "import Footer from './Footer';",
        "",
        "export default function Shell({ className, children }) {",
        "  return (",
        "    <main className={joinClasses('shell-frame', className)}>",
        '      <div className="shell-frame__body">{children}</div>',
        "      <Footer />",
        "    </main>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/layout/Footer.js",
      [
        "export default function Footer() {",
        '  return <footer className="site-footer muted-copy">Storefront demo</footer>;',
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/components/index.js",
      [
        "export { default as Button } from './Button';",
        "export { default as Modal } from './Modal';",
        "export { default as Navbar } from './Navbar';",
        "export { default as Price } from './Price';",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/components/Button.js",
      [
        "import { joinClasses } from '../utils/classNames';",
        "",
        "export default function Button({ tone = 'primary', loading, className, children }) {",
        '  const loadingNode = loading ? <span className="button__spinner" /> : null;',
        "  return (",
        "    <button className={joinClasses('btn', `btn-${tone}`, 'button', className)}>",
        "      {loadingNode}",
        '      <span className="button__label">{children}</span>',
        "    </button>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/components/Navbar.js",
      [
        "import { ThemeConsumer } from '../theme/ThemeContext';",
        "",
        "export default function Navbar() {",
        "  return (",
        "    <ThemeConsumer>",
        "      {({ theme }) => (",
        "        <nav className={theme === 'dark' ? 'navbar navbar-dark app-navbar app-navbar--dark' : 'navbar app-navbar'}>",
        '          <a className="navbar-brand app-navbar__brand" href="/">Storefront</a>',
        '          <a className="nav-link app-navbar__link" href="/cart">Cart</a>',
        "        </nav>",
        "      )}",
        "    </ThemeConsumer>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/components/Modal.js",
      [
        "import Button from './Button';",
        "",
        "export default function Modal() {",
        "  return (",
        '    <aside className="modal-panel server-only-badge">',
        '      <p className="modal-panel__copy">Added to cart</p>',
        '      <Button tone="secondary" className="modal-panel__action">Close</Button>',
        "    </aside>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/components/Price.js",
      [
        "export default function Price({ amount }) {",
        '  return <span className="price-tag">${amount}</span>;',
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/catalog/ProductList.js",
      [
        "import { ProductConsumer } from '../../state/ProductContext';",
        "import ProductCard from './components/ProductCard';",
        "import PromoRail from './components/PromoRail';",
        "",
        "export default function ProductList() {",
        "  return (",
        '    <section className="container product-list catalog-page">',
        '      <header className="catalog-page__header">',
        '        <h1 className="catalog-page__title">Featured gear</h1>',
        "      </header>",
        "      <ProductConsumer>",
        "        {({ products }) => (",
        '          <div className="row product-grid">',
        "            {products.map((product, index) => (",
        "              <ProductCard key={product.id} product={product} index={index} />",
        "            ))}",
        "          </div>",
        "        )}",
        "      </ProductConsumer>",
        "      <PromoRail />",
        "    </section>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/catalog/ProductDetails.js",
      [
        "import { ProductConsumer } from '../../state/ProductContext';",
        "import Button from '../../components/Button';",
        "import Price from '../../components/Price';",
        "",
        "export default function ProductDetails() {",
        "  return (",
        "    <ProductConsumer>",
        "      {({ featured }) => (",
        '        <article className="details-page details-page--ready">',
        '          <h1 className="details-page__title">{featured.title}</h1>',
        "          <Price amount={64} />",
        '          <Button className="details-page__button" loading>Add to cart</Button>',
        "        </article>",
        "      )}",
        "    </ProductConsumer>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/catalog/components/ProductCard.js",
      [
        "import Button from '../../../components/Button';",
        "import Price from '../../../components/Price';",
        "import ProductBadge from './ProductBadge';",
        "import { joinClasses, statusClass } from '../../../utils/classNames';",
        "",
        "export default function ProductCard({ product, index }) {",
        "  const featuredClass = product.featured ? 'product-card--featured' : 'product-card--standard';",
        "  const stockClass = statusClass('product-card', product.inStock);",
        "  const positionClass = index === 0 ? 'product-card--lead' : 'product-card--supporting';",
        "  return (",
        "    <article className={joinClasses('col-10 mx-auto product-card', featuredClass, stockClass, positionClass)}>",
        "      <ProductBadge featured={product.featured} />",
        '      <h2 className="product-card__title">{product.title}</h2>',
        "      <Price amount={42 + index} />",
        '      <Button className="product-card__action">Add to cart</Button>',
        "    </article>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/catalog/components/ProductBadge.js",
      [
        "export default function ProductBadge({ featured }) {",
        "  const labelClass = featured ? 'product-badge product-badge--featured' : 'product-badge';",
        "  return <span className={labelClass}>{featured ? 'Featured' : 'Standard'}</span>;",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/catalog/components/PromoRail.js",
      [
        "const promos = ['Free shipping', 'Bundle discount'];",
        "",
        "export default function PromoRail() {",
        "  return (",
        '    <aside className="promo-rail">',
        "      {promos.map((promo) => (",
        '        <p className="promo-rail__item" key={promo}>{promo}</p>',
        "      ))}",
        "    </aside>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withFile("src/features/cart/package.json", '{ "main": "Cart.js" }\n')
    .withSourceFile(
      "src/features/cart/index.js",
      [
        "export { default } from './Cart';",
        "export { default as CartSummary } from './CartSummary';",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/cart/Cart.js",
      [
        "import { ProductConsumer } from '../../state/ProductContext';",
        "import CartColumns from './CartColumns';",
        "import CartList from './CartList';",
        "import CartSummary from './CartSummary';",
        "import EmptyCart from './EmptyCart';",
        "",
        "export default function Cart() {",
        "  return (",
        '    <section className="cart-page h-full">',
        "      <ProductConsumer>",
        "        {({ cart, totals }) => (",
        "          cart.length > 0 ? (",
        "            <>",
        "              <CartColumns />",
        "              <CartList cart={cart} />",
        "              <CartSummary totals={totals} />",
        "            </>",
        "          ) : <EmptyCart />",
        "        )}",
        "      </ProductConsumer>",
        "    </section>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/cart/CartColumns.js",
      [
        "export default function CartColumns() {",
        '  return <header className="row cart-columns text-uppercase"><span className="col-10">Item</span></header>;',
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/cart/CartList.js",
      [
        "import CartItem from './CartItem';",
        "",
        "export default function CartList({ cart }) {",
        '  return <div className="cart-list">{cart.map((item) => <CartItem key={item.id} item={item} />)}</div>;',
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/cart/CartItem.js",
      [
        "import CartQuantity from './CartQuantity';",
        "",
        "export default function CartItem({ item }) {",
        "  return (",
        '    <div className="row cart-item">',
        '      <span className="col-10 mx-auto cart-item__title">{item.title}</span>',
        "      <CartQuantity count={item.id} />",
        "    </div>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/cart/CartQuantity.js",
      [
        "export default function CartQuantity({ count }) {",
        "  const quantityClass = count > 1 ? 'cart-quantity cart-quantity--many' : 'cart-quantity';",
        "  return <span className={quantityClass}>{count}</span>;",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/cart/CartSummary.js",
      [
        "import Button from '../../components/Button';",
        "",
        "export default function CartSummary({ totals }) {",
        "  return (",
        '    <footer className="cart-summary">',
        '      <p className="cart-summary__line">Subtotal: {totals.subtotal}</p>',
        '      <p className="cart-summary__line cart-summary__line--shipping">Shipping: {totals.shipping}</p>',
        '      <Button className="cart-summary__checkout">Checkout</Button>',
        "    </footer>",
        "  );",
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/features/cart/EmptyCart.js",
      [
        "export default function EmptyCart() {",
        '  return <p className="empty-cart h-full">Your cart is empty.</p>;',
        "}",
        "",
      ].join("\n"),
    )
    .withSourceFile(
      "src/routes/NotFound.js",
      [
        "export default function NotFound() {",
        '  return <section className="not-found-page"><h1 className="not-found-page__title">Missing page</h1></section>;',
        "}",
        "",
      ].join("\n"),
    )
    .withCssFile(
      "src/index.css",
      [
        "body { margin: 0; }",
        ".app-root { min-height: 100vh; }",
        ".legacy-reset { color: tomato; }",
        "",
      ].join("\n"),
    )
    .withCssFile(
      "src/App.css",
      [
        ".app-shell { min-height: 100vh; }",
        ".shell-frame { min-height: 100vh; }",
        ".shell-frame__body { min-height: 80vh; }",
        ".site-footer { padding: 1rem; }",
        ".muted-copy { color: #666; }",
        ".app-navbar { display: flex; }",
        ".app-navbar--dark { background: #111; }",
        ".app-navbar__brand { font-weight: 700; }",
        ".app-navbar__link { margin-left: auto; }",
        ".h-full { min-height: 100%; }",
        ".catalog-page { padding: 1rem; }",
        ".catalog-page__header { margin-bottom: 1rem; }",
        ".catalog-page__title { font-size: 1.5rem; }",
        ".product-list { padding: 1rem; }",
        ".product-grid { gap: 1rem; }",
        ".product-card { border: 1px solid #ddd; }",
        ".product-card--featured { border-color: #0d6efd; }",
        ".product-card--standard { border-color: #999; }",
        ".product-card--active { box-shadow: 0 0 0 2px #0d6efd; }",
        ".product-card--idle { opacity: 0.7; }",
        ".product-card--lead { order: -1; }",
        ".product-card--supporting { order: 0; }",
        ".product-card__title { font-weight: 700; }",
        ".product-card__action { margin-top: 0.5rem; }",
        ".product-badge { display: inline-flex; }",
        ".product-badge--featured { color: #0d6efd; }",
        ".promo-rail { display: grid; }",
        ".promo-rail__item { margin: 0; }",
        ".details-page { padding: 1rem; }",
        ".details-page--ready { opacity: 1; }",
        ".details-page__title { font-size: 2rem; }",
        ".details-page__button { margin-top: 1rem; }",
        ".button { display: inline-flex; }",
        ".button__spinner { width: 1rem; }",
        ".button__label { margin-inline-start: 0.25rem; }",
        ".price-tag { font-variant-numeric: tabular-nums; }",
        ".modal-panel { position: fixed; }",
        ".modal-panel__copy { margin: 0; }",
        ".modal-panel__action { margin-top: 1rem; }",
        ".cart-page { padding: 1rem; }",
        ".cart-columns { font-weight: 700; }",
        ".cart-list { display: grid; }",
        ".cart-item { padding: 0.5rem 0; }",
        ".cart-item__title { font-weight: 600; }",
        ".cart-quantity { min-width: 2rem; }",
        ".cart-quantity--many { color: #0d6efd; }",
        ".cart-summary { border-top: 1px solid #ddd; }",
        ".cart-summary__line { margin: 0; }",
        ".cart-summary__line--shipping { color: #555; }",
        ".cart-summary__checkout { margin-top: 1rem; }",
        ".empty-cart { color: #555; }",
        ".not-found-page { padding: 2rem; }",
        ".not-found-page__title { font-size: 2rem; }",
        ".stale-storefront-helper { opacity: 0; }",
        "",
      ].join("\n"),
    )
    .withNodeModuleFile(
      "bootstrap/dist/css/bootstrap.min.css",
      [
        ".navbar { display: flex; }",
        ".navbar-dark { color: white; }",
        ".navbar-brand { display: inline-block; }",
        ".nav-link { display: inline-block; }",
        ".container { width: 100%; }",
        ".row { display: flex; }",
        ".col-10 { flex: 0 0 83.333333%; }",
        ".mx-auto { margin-left: auto; margin-right: auto; }",
        ".btn { border: 1px solid transparent; }",
        ".btn-primary { color: white; }",
        ".btn-secondary { color: #111; }",
        ".text-uppercase { text-transform: uppercase; }",
        "",
      ].join("\n"),
    )
    .build();
}
