export { buildProjectSnapshot } from "./buildProjectSnapshot.js";
export { discoverProjectFileRecords } from "./files/discoverProjectFileRecords.js";

export type {
  HtmlScriptEdge,
  HtmlScriptSourceFact,
  HtmlScriptSourceInput,
  HtmlStylesheetEdge,
  HtmlStylesheetLinkFact,
  HtmlStylesheetLinkInput,
  JsonStaticValue,
  PackageCssImportEdge,
  PackageCssImportFact,
  PackageCssImportInput,
  ProjectBundlerConfigFile,
  ProjectBoundary,
  ProjectConfigFile,
  ProjectExternalCssSurface,
  ProjectFileDiscoveryResult,
  ProjectHtmlFile,
  ProjectJsonFile,
  ProjectResourceEdge,
  ProjectSnapshot,
  ProjectSnapshotFiles,
  ProjectSourceFile,
  ProjectStylesheetFile,
  SourceImportEdge,
  SourceImportFact,
  SourceImportKind,
  SourceImportLoading,
  StylesheetImportEdge,
  StylesheetImportFact,
} from "./types.js";
